version: '3.8'

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    external: true

volumes:
  dayd_mongo:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./containers/nginx:/etc/nginx
    entrypoint: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - daydreamer
    ports:
      - 80:80
      - 443:443
    networks:
      - external
      - internal

  daydreamer:
    hostname: daydreamer
    container_name: daydreamer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ${DEPENDENCIES:-/dev/null}:/var/www/node_modules
    networks:
      - internal
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - dayd_mongo:/data/db
    command: mongod
    restart: always
    networks:
      - internal
